PALABRAS = {
    "camisa": ["camisa", "cima", "masa", "mica", "casi", "asma", "misa", "sima", "saca", "as", "caia"],
    "platos": ["platos", "plato", "alto", "palo", "sol", "sal", "las", "sola", "paso", "pasto", "post", "talo", "topa", "ola", "tal", "ato"],
    "amigos": ["amigos", "amigo", "goma", "sima", "gas", "oiga", "sigo", "gamo", "mago", "soga", "isla", "mis", "asi"],
    "verdeo": ["verdeo", "verde", "ver", "red", "reo", "ore", "oido", "veo", "doy"],
    "tierra": ["tierra", "tira", "rata", "arte", "aire", "rita", "ira", "tar", "rara", "rie"],
    "puente": ["puente", "punte", "une", "ten"],
    "solado": ["solado", "sola", "lado", "sal", "ado", "osado", "ola", "las", "dos"],
    "botina": ["botina", "botin", "bota", "tina", "nota", "oia", "tan", "no", "ton", "tio", "iba"],
    "montar": ["montar", "manto", "tomar", "rato", "toma", "amo", "matar", "mano", "mora", "toro", "rota", "roma", "mato", "ramo"],
    "lanzas": ["lanzas", "lanza", "sal", "las", "ana", "alas", "nana"],
    "puerta": ["puerta", "puerto", "pura", "ruta", "tape", "pare", "pera", "tropa", "rapto", "puro", "pero", "trae"],
    "cuadro": ["cuadro", "rudo", "duro", "arduo", "cura", "dar", "oca", "arco"],
    "bodega": ["bodega", "boga", "daga", "goda", "dado"],
    "cobijo": ["cobijo", "ojo", "bicho", "cojo"],
    "trabas": ["trabas", "traba", "abra", "bar", "rata", "tras", "basa", "ras", "tasa"],
    "cuerda": ["cuerda", "cura", "ruda", "reda", "rueda", "cera", "dar", "cadera", "caer", "crea", "arce", "acre", "era"],
    "galopa": ["galopa", "gala", "lapa", "palo", "paga", "algo", "ola", "pago", "apaga"],
    "famosa": ["famosa", "fama", "soma", "masa", "amos", "osa", "fosa", "moza", "asoma"],
    "lentes": ["lentes", "lente", "entes"],
    "camion": ["camion", "cima", "mano", "mica", "mico", "oca", "con", "no", "oia", "camo", "cami"],
    "planta": ["planta", "plan", "pala", "tala", "nata", "tapa", "pana", "alta", "tal", "palta", "lana", "ala"],
    "marino": ["marino", "mar", "amor", "mina", "ramo", "mira", "rino", "oir", "arma", "roma", "mio"],
    "brillo": ["brillo", "rio", "rol"],
    "cobras": ["cobras", "cobra", "saco", "arco", "boca", "caro", "caso", "rabo", "roca", "barco", "cabo", "raso"],
    "lancha": ["lancha", "cana", "acha", "lana", "chal", "clan", "chala", "hala"],
    "colina": ["colina", "colin", "lino", "cola", "ola", "lona", "nilo", "calo"],
    "cabina": ["cabina", "bina", "baca", "cana", "iban", "naba"],
    "sombra": ["sombra", "broma", "soba", "roma", "raso", "mora", "sobra", "bar", "boa"],
    "escudo": ["escudo", "sueco", "codo", "eco", "dos", "uso", "duro", "rudo", "sed"],
    "torres": ["torres", "torre", "resto", "rotes", "tres", "ore", "sor", "rotos", "res"],
    "balazo": ["balazo", "bala", "lazo", "bazo", "ala", "azo", "bol"],
    "cuchara": ["cuchara", "cucha", "chara", "cura", "haca", "arca", "caer", "raza", "ucha", "cara"],
    "peinar": ["peinar", "peina", "pina", "reina", "pane", "pena", "aire", "pierna", "iran", "rie"],
    "sabana": ["sabana", "saba", "bana", "naba", "sana", "asa", "san", "ana"],
    "torneo": ["torneo", "norte", "tenor", "tono", "reto", "oro", "ron", "terco", "reo"],
    "camino": ["camino", "camino", "manco", "mano", "cima", "camo", "mino", "naco", "mico", "cami"],
    "fresca": ["fresca", "fresa", "cafe", "cara", "arce", "fase", "seca", "acre", "ras"],
    "polvos": ["polvos", "polo", "solo", "poso", "sol", "vos", "oso"],
    "gorras": ["gorras", "gora", "rasgo", "saga", "gas", "rosa", "soga", "osar"],
    "tabaco": ["tabaco", "taba", "baco", "taco", "cabo", "boa", "cata", "acto", "bato", "toba"],
    "bancos": ["bancos", "banco", "canso", "cosa", "bano", "nos", "con", "son", "cano", "coba", "beso"],
    "campos": ["campos", "campo", "copas", "paco", "sopa", "capo", "posa", "cosa", "paso", "como", "amos"],
    "cables": ["cables", "cable", "bale", "sale", "cal", "les", "ceba", "besa"],
    "sillas": ["sillas", "silla", "sali", "lisa", "isla", "las"],
    "casita": ["casita", "citas", "casa", "tasa", "tas", "cita", "sita"],
    "cortes": ["cortes", "corte", "torce", "resto", "estro", "ore", "coser", "ser", "tres", "set"],
    "reinos": ["reinos", "reino", "serio", "nos", "seno", "orin", "roen", "sino"],
    "plazas": ["plazas", "plaza", "lapa", "pala", "alza", "sal", "las", "paz"],
    "tercio": ["tercio", "corte", "eco", "reto", "cero", "terco", "rocio", "rico"],
    "bronce": ["bronce", "cono", "cero", "cebo", "reo"],
    "aviones": ["aviones", "avion", "savia", "son", "aves", "nave", "via", "vino", "sano", "visa", "anis", "veo", "oia"],
    "colores": ["colores", "color", "sol", "loro", "roles", "celo", "creo", "roce", "leo"],
    "camelo": ["camelo", "melo", "lame", "mole", "cola", "mal", "ola", "come", "calmo"],
    "punos": ["punos", "puno", "sol", "nos", "uno", "no", "son"],
    "familia": ["familia", "mil", "fila", "mal", "lia", "fama", "llama"],
    "escuela": ["escuela", "celas", "saca", "sale", "sal", "las", "causa", "se", "acusa"],
    "botella": ["botella", "bote", "tela", "alto", "bello", "balle", "olla", "lote", "al", "leo"],
    "cocina": ["cocina", "coca", "cono", "cien", "cinc", "oia", "con"],
    "regalo": ["regalo", "ruego", "gala", "algo", "ola", "leo", "ore", "dar"],
    "fiesta": ["fiesta", "fase", "seta", "tes", "esta", "fia", "eje", "si"],
    "juegos": ["juegos", "juez", "uso", "ego", "egos"],
    "manana": ["manana", "mana", "ama", "ana"],
    "novios": ["novios", "vino", "no", "os", "son", "nos"],
    "cartera": ["cartera", "rata", "arte", "cara", "cera", "rara", "teca", "rata"],
    "cabeza": ["cabeza", "cabe", "casa", "caza", "caza", "haz", "baza", "abeza"],
    "dinero": ["dinero", "orden", "don", "rio", "dire", "dino", "red", "reo"],
    "ventana": ["ventana", "veta", "nata", "ante", "tan", "vena", "ana", "neto"],
    "cancion": ["cancion", "cana", "no", "cien", "con"],
    "musica": ["musica", "suma", "casi", "misa", "sima", "usa", "asi", "mas"],
    "deporte": ["deporte", "red", "peor", "reto", "pedro", "ote", "reo"],
    "colegio": ["colegio", "cole", "ocio", "eco", "oigo", "lego", "gol"],
    "trabajo": ["trabajo", "tarja", "bota", "bajo", "jaba", "taja", "bar", "ajo"],
    "computo": ["computo", "poco", "top", "poto", "tomo"],
    "celular": ["celular", "cura", "real", "azul", "luce", "claro", "crea", "caer"],
    "computadora": ["computadora", "coto", "puta", "tropa", "rata", "data", "dar", "amor", "poda", "cura"],
    "pijama": ["pijama", "paja", "ama", "paz", "aja"],
    "bolsillo": ["bolsillo", "bolso", "silo", "solo", "sol", "lio"],
    "almuerzo": ["almuerzo", "azul", "mar", "muro", "zum", "mozo", "mal", "mora"],
    "desayuno": ["desayuno", "uso", "don", "dos", "seda", "sano", "no"],
    "chocolate": ["chocolate", "cola", "tela", "lote", "chal", "hola", "choza", "taco", "ocho"],
    "television": ["television", "lente", "leo", "veo", "no", "sol"],
    "pelicula": ["pelicula", "lupa", "pila", "pule", "pica", "lice", "piel", "cura"],
    "internet": ["internet", "tener", "tren", "ente", "tres"],
    "tienda": ["tienda", "den", "dia", "tan", "ten", "tia"],
    "hospital": ["hospital", "alto", "salto", "piso", "ola", "palo", "sol", "sal"],
    "medico": ["medico", "miedo", "mico", "oido", "dice", "codo"],
    "camara": ["camara", "mar", "cara", "rama", "arca"],
    "viajes": ["viajes", "vea", "vas", "es", "via", "saje"],
    "pasaje": ["pasaje", "pasa", "aje", "gas", "paz", "as"],
    "aeropuerto": ["aeropuerto", "pero", "puro", "ropa", "ore", "reo", "rata"],
    "maleta": ["maleta", "mala", "tela", "lama", "lee", "mal", "ale"],
    "llaves": ["llaves", "lave", "ale", "las", "valle"],
    "libros": ["libros", "bolso", "sol", "rio", "bos"],
    "cuentos": ["cuentos", "cuento", "tus", "unos", "uno", "seco"],
    "pluma": ["pluma", "puma", "mal", "pula", "pul"],
    "dibujo": ["dibujo", "bujo", "dio", "dijo", "ojo"],
    "pintura": ["pintura", "pinta", "tira", "ruta", "una", "pin"]
}
