#palabras.py
PALABRAS_POR_NIVEL = {
    1: [  # Naturaleza
        "SOL", "LUNA", "CIELO", "NUBE", "MAR", "RIO", "FLOR", "ARBOL", "HOJA", "MONTAÑA",
        "LAGO", "ARENA", "VIENTO", "ROCA", "FUEGO", "HIELO", "NIEVE", "CAMPO", "OLAS", "VALLE",
        "BOSQUE", "LLUVIA", "TRUENO", "RELAMPAGO", "TIERRA", "SEMILLA", "PLANTA", "FRUTA", "HIERBA", "DESIERTO",
        "CASCADA", "TORMENTA", "ISLA", "VOLCAN", "OCASO", "AMANECER", "CIELOAZUL", "MUNDO", "FLUVIAL", "NATURALEZA"
    ],

    2: [  # Animales
        "GATO", "PERRO", "RATON", "PEZ", "PATO", "LEON", "TIGRE", "CABALLO", "OVEJA", "ZORRO",
        "LOBO", "VACA", "CABRA", "BURRO", "CONEJO", "DELFIN", "AGUILA", "GORILA", "PINGUINO", "ELEFANTE",
        "TORTUGA", "SERPIENTE", "ARDILLA", "CAMELLO", "RINOCERONTE", "JIRAFA", "COCODRILO", "CANGURO", "FOCA", "GALLINA",
        "POLLO", "GAVIOTA", "CARACOL", "MARIPOSA", "ABEJA", "MOSCA", "ARAÑA", "CABALLITO", "BUHO", "CASTOR"
    ],

    3: [  # Objetos
        "MESA", "SILLA", "PUERTA", "VENTANA", "PARED", "VASO", "CUADERNO", "LAPIZ", "LIBRO", "CUCHILLO",
        "CUCHARA", "PLATO", "TELEVISOR", "CELULAR", "RELOJ", "BOTELLA", "BILLETERA", "ZAPATO", "LLAVE", "MOCHILA",
        "AURICULAR", "CAMARA", "CUADRO", "LINTERNA", "ESCOBA", "BOLSA", "GAFAS", "PANTALON", "CAMISA", "CHAQUETA",
        "ALMOHADA", "COLCHON", "SABANA", "CORTINA", "HELADERA", "MICROONDAS", "HORNO", "ESPEJO", "CANDADO", "BARRA"
    ],

    4: [  # Tecnología
        "COMPUTADORA", "TECLADO", "PANTALLA", "MOUSE", "CABLE", "PROCESADOR", "MONITOR", "IMPRESORA", "ROUTER", "SERVIDOR",
        "INTERNET", "ARCHIVO", "PROGRAMA", "JUEGO", "CELULAR", "TABLET", "MEMORIA", "DISCO", "BATERIA", "SISTEMA",
        "RED", "CONEXION", "MICROCHIP", "DATOS", "USB", "PLACA", "SENSOR", "ANTENA", "ALTAVOZ", "MICROFONO",
        "CAMARA", "NUBE", "PROYECTOR", "DRON", "SMARTPHONE", "LAPTOP", "SOFTWARE", "HARDWARE", "BASEDEDATOS", "PANTALLALED"
    ],

    5: [  # Nivel experto - Programación / informática
        "PROGRAMACION", "ALGORITMO", "VARIABLE", "FUNCION", "COMPILADOR", "CODIGO", "MODULO", "ARGUMENTO", "BUCLE", "OPERADOR",
        "PYTHON", "JAVASCRIPT", "BIBLIOTECA", "PARAMETRO", "ESTRUCTURA", "CONSTANTE", "ENTORNO", "DEBUG", "OBJETO", "LISTA",
        "DICCIONARIO", "CLASE", "HERENCIA", "MODULARIDAD", "PROYECTO", "SINTAXIS", "DEPENDENCIA", "CONTROLADOR", "INTERFAZ", "SERVIDORWEB",
        "JSON", "CSV", "BASEDEDATOS", "FRAMEWORK", "ALMACENAMIENTO", "ITERACION", "RECURRENCIA", "COMENTARIO", "FUNCIONAL", "BINARYTREE"
    ]
}
